version: 0.0
os: linux

files:
  - source: /
    destination: /usr/local/debrainsApi
permissions:
  - object: /usr/local/debrainsApi
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root