= REST API Guide
Debrains;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response
ifndef::snippets[]
:snippets: ./build/generated-snippets
endif::[]

[[overview]]
= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `PATCH`
| 기존 리소스의 일부를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `204 No Content`
| 기존 리소스를 성공적으로 수정함.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `404 Not Found`
| 요청한 리소스가 없음.
|===


[[overview-hypermedia]]
== 하이퍼미디어

본 REST API는 하이퍼미디어와 사용하며 응답에 담겨있는 리소스는 다른 리소스에 대한 링크를 가지고 있다.
응답은 http://stateless.co/hal_specification.html[Hypertext Application from resource to resource. Language (HAL)] 형식을 따른다.
링크는 `_links`라는 키로 제공한다. 본 API의 사용자(클라이언트)는 URI를 직접 생성하지 않아야 하며, 리소스에서 제공하는 링크를 사용해야 한다.

[[resources]]
= 리소스

[[resources-index]]
== 인덱스

인덱스는 서비스 진입점을 제공한다.

[[resources-index-access]]
=== 인덱스 조회

`GET` 요청을 사용하여 인덱스에 접근할 수 있다.

operation::index[snippets='response-body,http-response,links']

[[resources-support]]
== SUPPORT
SUPPORT 리소스는 고객센터를 다룰 때 사용한다.

[[resources-support-notice-list]]
=== 공지사항 리스트 조회
`GET` 요청으로 공지사항 리스트를 조회한다.

operation::get-noticeList[snippets='http-request,request-headers,http-response,response-headers,response-fields,links']

[[resources-support-notice]]
=== 공지사항 조회
`GET` 요청으로 공지사항 하나를 조회한다.

operation::get-notice[snippets='http-request,request-headers,http-response,response-headers,response-fields,links']

[[resources-support-event-list]]
=== 이벤트 리스트 조회
`GET` 요청으로 이벤트 리스트를 조회한다.

operation::get-eventList[snippets='http-request,request-headers,http-response,response-headers,response-fields,links']

[[resources-support-event]]
=== 이벤트 조회
`GET` 요청으로 이벤트 하나를 조회한다.

operation::get-event[snippets='http-request,request-headers,http-response,response-headers,response-fields,links']

[[resources-support-qna-get]]
=== QnA 조회
`GET` 요청으로 QnA 하나를 조회한다.

operation::get-qna[snippets='http-request,request-headers,http-response,response-headers,response-fields,links']

[[resources-support-qna-save]]
=== QnA 제출
`POST` 요청으로 QnA를 제출한다.

operation::save-qna[snippets='http-request,request-headers,request-fields,http-response,response-headers,response-fields,links']


[[resources-support-skill-request]]
=== 프로필 스킬 추가요청
`POST` 요청으로 프로필의 스킬리스트에 스킬을 추가요청한다.

operation::request-skill[snippets='http-request,request-headers,request-fields,http-response,response-headers']





[[resources-tils]]
== TIL
TIL 리소스는 TIL을 다룰 때 사용한다.

[[resources-tils-list]]
=== TIL 목록 조회
`GET` 요청으로 TIL 리스트를 조회한다.

operation::get-tilList[snippets='http-request,http-response,response-headers,response-fields,links']


[[resources-tils-create]]
=== TIL 생성
`POST` 요청을 사용해서 TIL을 만든다.

operation::create-til[snippets='http-request,request-headers,request-fields,http-response,response-headers,response-fields,links']


[[resources-tils-get]]
=== TIL 조회
`GET` 요청으로 TIL 하나를 조회한다.

operation::get-til[snippets='http-request,path-parameters,http-response,response-headers,response-fields,links']


[[resources-tils-update]]
=== TIL 수정
`PATCH` 요청을 사용해서 TIL를 수정할 수 있다.

operation::update-til[snippets='http-request,request-headers,path-parameters,request-fields,http-response,response-headers,response-fields,links']



[[resources-til-crts]]
== TIL 인증
TIL 인증 리소스는 TIL 인증을 다룰 때 사용한다.

[[resources-til-crts-list]]
=== TIL 인증 목록 조회
`GET` 요청으로 TIL 인증 리스트를 조회한다.

operation::get-tilcrtList[snippets='http-request,http-response,response-headers,response-fields,links']


[[resources-til-crts-create]]
=== TIL 인증 생성
`POST` 요청을 사용해서 TIL 인증을 만든다.

operation::create-tilcrt[snippets='http-request,request-headers,request-fields,http-response,response-headers,response-fields,links']


[[resources-til-crts-get]]
=== TIL 인증 조회
`GET` 요청으로 TIL 인증 하나를 조회한다.

operation::get-tilcrt[snippets='http-request,path-parameters,http-response,response-headers,response-fields,links']


[[resources-til-crts-update]]
=== TIL 인증 수정
`PATCH` 요청을 사용해서 TIL 인증을 수정할 수 있다.

operation::update-tilcrt[snippets='http-request,request-headers,path-parameters,request-fields,http-response,response-headers,response-fields,links']



[[resources-user]]
== USER
USER 리소스는 유저정보를 다룰 때 사용한다.

[[resources-user-get]]
=== 유저정보 조회
`GET` 요청으로 현재 로그인한 유저정보를 조회한다.

operation::get-userInfo[snippets='http-request,request-headers,http-response,response-headers,response-fields,links']

[[resources-user-update]]
=== 유저정보 수정
`PATCH` 요청으로 유저정보를 수정한다.

operation::save-userInfo[snippets='http-request,request-headers,request-fields,http-response,response-headers,response-fields,links']

[[resources-user-nameValidate]]
=== 유저정보 닉네임 중복검사
`POST` 요청으로 유저정보 수정시 닉네임 중복검사를 한다.

operation::validate-name[snippets='http-request,request-headers,request-fields,http-response,response-headers,response-fields']

[[resources-user-profile-get]]
=== 유저프로필 조회
`GET` 요청으로 현재 로그인한 유저프로필을 조회한다.

operation::get-userProfile[snippets='http-request,request-headers,http-response,response-headers,response-fields,links']

[[resources-user-profile-update]]
=== 유저프로필 수정
`PATCH` 요청으로 유저프로필을 수정한다.

operation::save-userProfile[snippets='http-request,request-headers,request-fields,http-response,response-headers,response-fields,links']

[[resources-user-board-get]]
=== 유저보드 조회
`GET` 요청으로 유저정보와 프로필이 결합되어 출력되는 유저보드를 조회한다.

operation::get-userBoard[snippets='http-request,request-headers,http-response,response-headers,response-fields,links']

[[resources-user-qnaList-get]]
=== My QnA 리스트 조회
`GET` 요청으로 현재 로그인한 유저의 QnA리스트를 조회한다.

operation::get-userQnaList[snippets='http-request,request-headers,http-response,response-headers,response-fields,links']
