name: deploy-staging

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Github-Actions
        uses: actions/checkout@v2

      - name: Install Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      
      - name: Permission for Gradle 
        run: chmod +x ./gradlew

      - name: Start Build with Gradle
        run: ./gradlew clean build

      - name: Setting for AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Upload to S3
        run: aws deploy push --application-name debrainsApi --description "Debraions API Test" --s3-location s3://debrain.co.kr/deploy/debrainsApi-staging.zip --source .

      - name: Start Deploy with CodeDeploy
        run: aws deploy create-deployment --application-name debrainsApi --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name debrainsApi-staging --s3-location bucket=debrains.co.kr,bundleType=zip,key=deploy/debrainsApi-staging.zip


